<?php
// Do not edit this file!
// Use configure with the right parameters, and run 'make' and 'make install'
// Variables you can change are in common-config.php and domserver-config.php

// Generated from 'domserver-static.php.in' on Thu Sep 21 20:56:09 ICT 2017.

define('DOMJUDGE_VERSION', '5.1.3');

define('BINDIR',      '/var/www/contest/domserver/bin');
define('ETCDIR',      '/var/www/contest/domserver/etc');
define('WWWDIR',      '/var/www/contest/domserver/www');
define('LIBDIR',      '/var/www/contest/domserver/lib');
define('LIBEXTDIR',   '/var/www/contest/domserver/lib/ext');
define('LIBWWWDIR',   '/var/www/contest/domserver/lib/www');
define('LIBSUBMITDIR','/var/www/contest/domserver/lib/submit');
define('LOGDIR',      '/var/www/contest/domserver/log');
define('RUNDIR',      '/var/www/contest/domserver/run');
define('TMPDIR',      '/var/www/contest/domserver/tmp');
define('SUBMITDIR',   '/var/www/contest/domserver/submissions');

define('SUBMITCLIENT_ENABLED', 'yes');

set_include_path(get_include_path() . PATH_SEPARATOR . LIBEXTDIR);
