<?php
// Do not edit this file!
// Use configure with the right parameters, and run 'make' and 'make install'
// Variables you can change are in common-config.php and judgehost-config.php

// Generated from 'judgehost-static.php.in' on Thu Sep 21 20:56:09 ICT 2017.

define('DOMJUDGE_VERSION', '5.1.3');

define('BINDIR',      '/var/www/contest/judgehost/bin');
define('ETCDIR',      '/var/www/contest/judgehost/etc');
define('LIBDIR',      '/var/www/contest/judgehost/lib');
define('LIBEXTDIR',   '/var/www/contest/judgehost/lib/ext');
define('LIBJUDGEDIR', '/var/www/contest/judgehost/lib/judge');
define('LOGDIR',      '/var/www/contest/judgehost/log');
define('RUNDIR',      '/var/www/contest/judgehost/run');
define('TMPDIR',      '/var/www/contest/judgehost/tmp');
define('JUDGEDIR',    '/var/www/contest/judgehost/judgings');
define('CHROOTDIR',   '/chroot/domjudge');

define('RUNUSER',     'domjudge-run');
define('USE_CGROUPS', '1');

// Possible exitcodes from testcase_run.sh and their meaning.
$EXITCODES = array (
	0   => 'correct',
	101 => 'compiler-error',
	102 => 'timelimit',
	103 => 'run-error',
	104 => 'no-output',
	105 => 'wrong-answer',
//	106 => 'presentation-error', /* dropped since 5.0 */
	107 => 'memory-limit', /* not in use internally */
	108 => 'output-limit',
/* Uncomment the next line(s) to accept internal errors in the judging
 * backend as outcome. WARNING: it is highly discouraged to enable
 * this, as the judgehost may be in an inconsistent state after an
 * internal error occurred and it is recommended to inspect manually.
 */
//	127 => 'internal-error',
//	128 => 'compare-error',
	);
